version: '3.8'

services:
  bot:
    build: .
    container_name: binance_crypto_bot
    restart: always
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python main.py

